// Generated by Tools/gen-rsvp-spec.mjs from Tools/rsvp-spec.json. DO NOT EDIT.
// Edit the spec and re-run the generator; CI drift-gates this file.

/* eslint-disable */
export const RSVP_SPEC = {
  version: 1,
  wpm: {
    default: 450,
    minimumSafe: 100,
    maximum: 1500,
    step: 25,
    minimumUser: { latin: 300, cjk: 150 },
  },
  duration: {
    baseMillisPerMinute: 60000,
    cjkMultiplier: 1.5,
    lengthThreshold: 9,
    lengthPerCharIncrement: 0.07,
    lengthMaxIncrement: 0.6,
    pauseMultiplier: 1.65,
  },
  ranges: {
    cjk: [[0x3040, 0x30FF], [0x3400, 0x4DBF], [0x4E00, 0x9FFF], [0xF900, 0xFAFF], [0xAC00, 0xD7AF]],
    han: [[0x3400, 0x4DBF], [0x4E00, 0x9FFF], [0xF900, 0xFAFF]],
    cjkPunctuation: [[0x3000, 0x303F], [0xFF00, 0xFFEF]],
  },
  punctuation: {
    asciiPause: [".", ",", "!", "?", ";", ":"],
    latinSentenceEnd: [".", "!", "?", ";", ":", ")"],
    latinTrailingClosers: ["\"", "'", ")", "]"],
  },
  chunkShaper: {
    maxMergedCJK: 4,
    possessiveDe: "的",
    measureWords: ["個", "位", "件", "種", "名", "次", "回", "張", "把", "條", "場", "份", "年", "月", "日", "時", "分", "秒", "週", "季", "點", "天", "小時", "分鐘", "秒鐘", "公斤", "公克", "公尺", "公里", "公分", "公升", "元", "塊", "毛", "億", "萬", "度", "個月", "個人", "歲"],
    prepositionsForCompound: ["在", "從", "到", "向", "於"],
    particlesBackward: ["了", "著", "過", "之", "矣", "哉", "焉", "乎", "而", "嗎", "呢", "吧", "啊", "喔", "耶", "呀", "嘛", "呵"],
    particlesForward: ["在", "從", "對", "向", "把", "被", "給", "及", "或", "是", "為", "也", "又", "都", "還", "才", "就", "便", "很", "更", "最", "太", "不", "沒", "未", "別", "新", "舊"],
    pronouns: ["我", "你", "他", "她", "它", "您", "咱", "妳"],
    peelForwardVerbs: ["去", "來", "回", "走", "上", "下", "進", "出", "看", "說", "講", "做", "想", "聽", "讀", "寫", "吃", "喝", "買", "賣", "找"],
    hardClauseEndings: ["。", "，", "！", "？", "；", "：", "」", "』", "）", "》", "〉", ".", ",", "!", "?", ";", ":"],
  },
} as const;
