// Generated by Tools/gen-rsvp-spec.mjs from Tools/rsvp-spec.json. DO NOT EDIT.
// Edit the spec and re-run the generator; CI drift-gates this file.
import Foundation

enum RSVPSpec {
    static let version: Int = 1

    enum WPM {
        static let `default`: Double = 450
        static let minimumSafe: Double = 100
        static let maximum: Double = 1500
        static let step: Double = 25
        static let minimumUserLatin: Double = 300
        static let minimumUserCJK: Double = 150
    }

    enum Duration {
        static let baseMillisPerMinute: Double = 60000
        static let cjkMultiplier: Double = 1.5
        static let lengthThreshold: Int = 9
        static let lengthPerCharIncrement: Double = 0.07
        static let lengthMaxIncrement: Double = 0.6
        static let pauseMultiplier: Double = 1.65
    }

    static let cjkRanges: [ClosedRange<UInt32>] = [0x3040...0x30FF, 0x3400...0x4DBF, 0x4E00...0x9FFF, 0xF900...0xFAFF, 0xAC00...0xD7AF]
    static let hanRanges: [ClosedRange<UInt32>] = [0x3400...0x4DBF, 0x4E00...0x9FFF, 0xF900...0xFAFF]
    static let cjkPunctuationRanges: [ClosedRange<UInt32>] = [0x3000...0x303F, 0xFF00...0xFFEF]

    @inline(__always) static func isCJKScalar(_ v: UInt32) -> Bool { (v >= 0x3040 && v <= 0x30FF) || (v >= 0x3400 && v <= 0x4DBF) || (v >= 0x4E00 && v <= 0x9FFF) || (v >= 0xF900 && v <= 0xFAFF) || (v >= 0xAC00 && v <= 0xD7AF) }
    @inline(__always) static func isHanScalar(_ v: UInt32) -> Bool { (v >= 0x3400 && v <= 0x4DBF) || (v >= 0x4E00 && v <= 0x9FFF) || (v >= 0xF900 && v <= 0xFAFF) }
    @inline(__always) static func isCJKPunctuationScalar(_ v: UInt32) -> Bool { (v >= 0x3000 && v <= 0x303F) || (v >= 0xFF00 && v <= 0xFFEF) }

    static let asciiPause: Set<Character> = [".", ",", "!", "?", ";", ":"]
    static let latinSentenceEnd: Set<Character> = [".", "!", "?", ";", ":", ")"]
    static let latinTrailingClosers: Set<Character> = ["\"", "'", ")", "]"]

    enum ChunkShaper {
        static let maxMergedCJK: Int = 4
        static let possessiveDe: Character = "的"
        static let measureWords: Set<String> = ["個", "位", "件", "種", "名", "次", "回", "張", "把", "條", "場", "份", "年", "月", "日", "時", "分", "秒", "週", "季", "點", "天", "小時", "分鐘", "秒鐘", "公斤", "公克", "公尺", "公里", "公分", "公升", "元", "塊", "毛", "億", "萬", "度", "個月", "個人", "歲"]
        static let prepositionsForCompound: Set<Character> = ["在", "從", "到", "向", "於"]
        static let particlesBackward: Set<Character> = ["了", "著", "過", "之", "矣", "哉", "焉", "乎", "而", "嗎", "呢", "吧", "啊", "喔", "耶", "呀", "嘛", "呵"]
        static let particlesForward: Set<Character> = ["在", "從", "對", "向", "把", "被", "給", "及", "或", "是", "為", "也", "又", "都", "還", "才", "就", "便", "很", "更", "最", "太", "不", "沒", "未", "別", "新", "舊"]
        static let pronouns: Set<Character> = ["我", "你", "他", "她", "它", "您", "咱", "妳"]
        static let peelForwardVerbs: Set<Character> = ["去", "來", "回", "走", "上", "下", "進", "出", "看", "說", "講", "做", "想", "聽", "讀", "寫", "吃", "喝", "買", "賣", "找"]
        static let hardClauseEndings: Set<Character> = ["。", "，", "！", "？", "；", "：", "」", "』", "）", "》", "〉", ".", ",", "!", "?", ";", ":"]
    }
}
