// Generated by Tools/gen-rsvp-spec.mjs from Tools/rsvp-spec.json. DO NOT EDIT.
// Edit the spec and re-run the generator; CI drift-gates this file.

package com.shhtheonlyperson.fastread.spike.core

object RsvpSpec {
    const val VERSION = 1

    object Wpm {
        const val DEFAULT = 450.0
        const val MINIMUM_SAFE = 100.0
        const val MAXIMUM = 1500.0
        const val STEP = 25.0
        const val MINIMUM_USER_LATIN = 300.0
        const val MINIMUM_USER_CJK = 150.0
    }

    object Duration {
        const val BASE_MILLIS_PER_MINUTE = 60000.0
        const val CJK_MULTIPLIER = 1.5
        const val LENGTH_THRESHOLD = 9
        const val LENGTH_PER_CHAR_INCREMENT = 0.07
        const val LENGTH_MAX_INCREMENT = 0.6
        const val PAUSE_MULTIPLIER = 1.65
    }

    val cjkRanges = listOf(0x3040..0x30FF, 0x3400..0x4DBF, 0x4E00..0x9FFF, 0xF900..0xFAFF, 0xAC00..0xD7AF)
    val hanRanges = listOf(0x3400..0x4DBF, 0x4E00..0x9FFF, 0xF900..0xFAFF)
    val cjkPunctuationRanges = listOf(0x3000..0x303F, 0xFF00..0xFFEF)

    val asciiPause = setOf('.', ',', '!', '?', ';', ':')
    val latinSentenceEnd = setOf('.', '!', '?', ';', ':', ')')
    val latinTrailingClosers = setOf('"', '\'', ')', ']')

    object ChunkShaper {
        const val MAX_MERGED_CJK = 4
        const val POSSESSIVE_DE = '的'
        val measureWords = setOf("個", "位", "件", "種", "名", "次", "回", "張", "把", "條", "場", "份", "年", "月", "日", "時", "分", "秒", "週", "季", "點", "天", "小時", "分鐘", "秒鐘", "公斤", "公克", "公尺", "公里", "公分", "公升", "元", "塊", "毛", "億", "萬", "度", "個月", "個人", "歲")
        val prepositionsForCompound = setOf('在', '從', '到', '向', '於')
        val particlesBackward = setOf('了', '著', '過', '之', '矣', '哉', '焉', '乎', '而', '嗎', '呢', '吧', '啊', '喔', '耶', '呀', '嘛', '呵')
        val particlesForward = setOf('在', '從', '對', '向', '把', '被', '給', '及', '或', '是', '為', '也', '又', '都', '還', '才', '就', '便', '很', '更', '最', '太', '不', '沒', '未', '別', '新', '舊')
        val pronouns = setOf('我', '你', '他', '她', '它', '您', '咱', '妳')
        val peelForwardVerbs = setOf('去', '來', '回', '走', '上', '下', '進', '出', '看', '說', '講', '做', '想', '聽', '讀', '寫', '吃', '喝', '買', '賣', '找')
        val hardClauseEndings = setOf('。', '，', '！', '？', '；', '：', '」', '』', '）', '》', '〉', '.', ',', '!', '?', ';', ':')
    }
}
